/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.gui;

/**
 *
 * @author raven
 */
public class AdminOkno extends javax.swing.JFrame {

    /**
     * Creates new form UvodneOkno
     */
    public AdminOkno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        vyhladavajPodlaButtonGroup = new javax.swing.ButtonGroup();
        vyhladajButtonGroup = new javax.swing.ButtonGroup();
        vyhladavaciPanePanel = new javax.swing.JPanel();
        vyhladavajPodlaLabel = new javax.swing.JLabel();
        knihuPodlaLabel = new javax.swing.JLabel();
        hladajKnihuRadioButton = new javax.swing.JRadioButton();
        hladajAutoraRadioButton = new javax.swing.JRadioButton();
        nazvuRadioButton = new javax.swing.JRadioButton();
        zanruRadioButton = new javax.swing.JRadioButton();
        autoraRadioButton = new javax.swing.JRadioButton();
        jazykaRadioButton = new javax.swing.JRadioButton();
        TabulkaKnihScrollPane = new javax.swing.JScrollPane();
        knihyTable = new javax.swing.JTable();
        vyhladajComboBox = new javax.swing.JComboBox<>();
        vyhladajButton = new javax.swing.JButton();
        pridajAutoraButton = new javax.swing.JButton();
        OdhlasSaButton = new javax.swing.JButton();
        pridajKnihuButton = new javax.swing.JButton();
        nazovTextField = new javax.swing.JTextField();
        urlTextField = new javax.swing.JTextField();
        pocetStranTextField = new javax.swing.JTextField();
        autorTextField = new javax.swing.JTextField();
        zanerComboBox = new javax.swing.JComboBox<>();
        formatComboBox = new javax.swing.JComboBox<>();
        jazykComboBox = new javax.swing.JComboBox<>();
        jazyk2ComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        oAutoroviScrollPane = new javax.swing.JScrollPane();
        popisAutoraTextArea = new javax.swing.JTextArea();
        oKniheScrollPane = new javax.swing.JScrollPane();
        popisKnihyTextArea = new javax.swing.JTextArea();
        menoAutoraTextField = new javax.swing.JTextField();
        priezviskoAutoraTextField = new javax.swing.JTextField();
        stredneMenoAutoraTextField = new javax.swing.JTextField();
        fotkaAutoraTextField = new javax.swing.JTextField();
        menoAutoraLabel = new javax.swing.JLabel();
        priezviskoAutoraLabel = new javax.swing.JLabel();
        fotkaAutoraLabel = new javax.swing.JLabel();
        stredneMenoAutoraLabel = new javax.swing.JLabel();
        zanerLabel = new javax.swing.JLabel();
        formatLabel = new javax.swing.JLabel();
        jazykLabel = new javax.swing.JLabel();
        jazyk2Label = new javax.swing.JLabel();
        autorLabel = new javax.swing.JLabel();
        nazovLabel = new javax.swing.JLabel();
        urlLabel = new javax.swing.JLabel();
        pocetStranLabel = new javax.swing.JLabel();
        zmenAutoraButton = new javax.swing.JButton();
        zmenKnihuButton = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Virtuálna knižnica");
        setMinimumSize(new java.awt.Dimension(900, 710));

        vyhladavajPodlaLabel.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        vyhladavajPodlaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vyhladavajPodlaLabel.setText("Vyhľadaj:");

        knihuPodlaLabel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        knihuPodlaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        knihuPodlaLabel.setText("Knihu podľa:");

        vyhladajButtonGroup.add(hladajKnihuRadioButton);
        hladajKnihuRadioButton.setSelected(true);
        hladajKnihuRadioButton.setText("Knihu");
        hladajKnihuRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hladajKnihuRadioButtonActionPerformed(evt);
            }
        });

        vyhladajButtonGroup.add(hladajAutoraRadioButton);
        hladajAutoraRadioButton.setText("Autora");
        hladajAutoraRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hladajAutoraRadioButtonActionPerformed(evt);
            }
        });

        vyhladavajPodlaButtonGroup.add(nazvuRadioButton);
        nazvuRadioButton.setSelected(true);
        nazvuRadioButton.setText("Názvu");

        vyhladavajPodlaButtonGroup.add(zanruRadioButton);
        zanruRadioButton.setText("Žánru");

        vyhladavajPodlaButtonGroup.add(autoraRadioButton);
        autoraRadioButton.setText("Autora");

        vyhladavajPodlaButtonGroup.add(jazykaRadioButton);
        jazykaRadioButton.setText("Jazyka");

        javax.swing.GroupLayout vyhladavaciPanePanelLayout = new javax.swing.GroupLayout(vyhladavaciPanePanel);
        vyhladavaciPanePanel.setLayout(vyhladavaciPanePanelLayout);
        vyhladavaciPanePanelLayout.setHorizontalGroup(
            vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vyhladavaciPanePanelLayout.createSequentialGroup()
                .addGroup(vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(knihuPodlaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(vyhladavaciPanePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jazykaRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autoraRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vyhladavajPodlaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hladajAutoraRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(vyhladavaciPanePanelLayout.createSequentialGroup()
                                .addGroup(vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nazvuRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(zanruRadioButton)
                                    .addComponent(hladajKnihuRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        vyhladavaciPanePanelLayout.setVerticalGroup(
            vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vyhladavaciPanePanelLayout.createSequentialGroup()
                .addComponent(vyhladavajPodlaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hladajKnihuRadioButton)
                    .addComponent(hladajAutoraRadioButton))
                .addGap(8, 8, 8)
                .addComponent(knihuPodlaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazvuRadioButton)
                    .addComponent(autoraRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zanruRadioButton)
                    .addComponent(jazykaRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        knihyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabulkaKnihScrollPane.setViewportView(knihyTable);

        vyhladajComboBox.setEditable(true);
        vyhladajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        vyhladajButton.setText("Hľadaj");
        vyhladajButton.setMaximumSize(new java.awt.Dimension(90, 35));
        vyhladajButton.setMinimumSize(new java.awt.Dimension(90, 35));

        pridajAutoraButton.setText("Pridaj autora");

        OdhlasSaButton.setText("Odhlás sa");

        pridajKnihuButton.setText("Pridaj knihu");
        pridajKnihuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajKnihuButtonActionPerformed(evt);
            }
        });

        zanerComboBox.setEditable(true);
        zanerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        formatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jazykComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jazyk2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        oAutoroviScrollPane.setMaximumSize(new java.awt.Dimension(130, 130));

        popisAutoraTextArea.setColumns(20);
        popisAutoraTextArea.setRows(5);
        popisAutoraTextArea.setText("O autorovi");
        popisAutoraTextArea.setToolTipText("");
        popisAutoraTextArea.setMaximumSize(new java.awt.Dimension(130, 75));
        popisAutoraTextArea.setPreferredSize(new java.awt.Dimension(150, 75));
        oAutoroviScrollPane.setViewportView(popisAutoraTextArea);

        popisKnihyTextArea.setColumns(20);
        popisKnihyTextArea.setLineWrap(true);
        popisKnihyTextArea.setRows(5);
        popisKnihyTextArea.setText("Popis knihy");
        oKniheScrollPane.setViewportView(popisKnihyTextArea);

        menoAutoraLabel.setText("Meno:");

        priezviskoAutoraLabel.setText("Priezvisko:");

        fotkaAutoraLabel.setText("Fotka:");

        stredneMenoAutoraLabel.setText("Stredne meno:");

        zanerLabel.setText("Žáner:");

        formatLabel.setText("Formát:");

        jazykLabel.setText("Jazyk:");

        jazyk2Label.setText("Jazyk 2:");

        autorLabel.setText("Autor:");

        nazovLabel.setText("Názov:");

        urlLabel.setText("URL:");

        pocetStranLabel.setText("Počet strán:");

        zmenAutoraButton.setText("Zmeň autora");

        zmenKnihuButton.setText("Zmeň knihu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pocetStranLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(urlLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nazovLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(autorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(urlTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pocetStranTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(autorTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nazovTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(formatLabel)
                                    .addComponent(zanerLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(zanerComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 200, Short.MAX_VALUE)
                                    .addComponent(formatComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jazyk2Label)
                                    .addComponent(jazykLabel))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jazykComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jazyk2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vyhladajComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(vyhladajButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addComponent(TabulkaKnihScrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(priezviskoAutoraLabel)
                            .addComponent(menoAutoraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menoAutoraTextField)
                            .addComponent(priezviskoAutoraTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stredneMenoAutoraLabel)
                            .addComponent(fotkaAutoraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stredneMenoAutoraTextField)
                            .addComponent(fotkaAutoraTextField))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vyhladavaciPanePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oKniheScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(oAutoroviScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pridajAutoraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zmenAutoraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pridajKnihuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(zmenKnihuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(OdhlasSaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vyhladajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vyhladajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TabulkaKnihScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nazovTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazovLabel)
                            .addComponent(zanerLabel)
                            .addComponent(zanerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formatLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pocetStranTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pocetStranLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jazykComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jazykLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(autorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(autorLabel)
                                .addComponent(jazyk2Label))
                            .addComponent(jazyk2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(vyhladavaciPanePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pridajKnihuButton)
                            .addComponent(pridajAutoraButton))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zmenAutoraButton)
                            .addComponent(zmenKnihuButton))
                        .addGap(12, 12, 12)
                        .addComponent(oKniheScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oAutoroviScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stredneMenoAutoraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menoAutoraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(stredneMenoAutoraLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(menoAutoraLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priezviskoAutoraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotkaAutoraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priezviskoAutoraLabel)
                    .addComponent(fotkaAutoraLabel)
                    .addComponent(OdhlasSaButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hladajAutoraRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hladajAutoraRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hladajAutoraRadioButtonActionPerformed

    private void hladajKnihuRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hladajKnihuRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hladajKnihuRadioButtonActionPerformed

    private void pridajKnihuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajKnihuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pridajKnihuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOkno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OdhlasSaButton;
    private javax.swing.JScrollPane TabulkaKnihScrollPane;
    private javax.swing.JLabel autorLabel;
    private javax.swing.JTextField autorTextField;
    private javax.swing.JRadioButton autoraRadioButton;
    private javax.swing.JComboBox<String> formatComboBox;
    private javax.swing.JLabel formatLabel;
    private javax.swing.JLabel fotkaAutoraLabel;
    private javax.swing.JTextField fotkaAutoraTextField;
    private javax.swing.JRadioButton hladajAutoraRadioButton;
    private javax.swing.JRadioButton hladajKnihuRadioButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jazyk2ComboBox;
    private javax.swing.JLabel jazyk2Label;
    private javax.swing.JComboBox<String> jazykComboBox;
    private javax.swing.JLabel jazykLabel;
    private javax.swing.JRadioButton jazykaRadioButton;
    private javax.swing.JLabel knihuPodlaLabel;
    private javax.swing.JTable knihyTable;
    private javax.swing.JLabel menoAutoraLabel;
    private javax.swing.JTextField menoAutoraTextField;
    private javax.swing.JLabel nazovLabel;
    private javax.swing.JTextField nazovTextField;
    private javax.swing.JRadioButton nazvuRadioButton;
    private javax.swing.JScrollPane oAutoroviScrollPane;
    private javax.swing.JScrollPane oKniheScrollPane;
    private javax.swing.JLabel pocetStranLabel;
    private javax.swing.JTextField pocetStranTextField;
    private javax.swing.JTextArea popisAutoraTextArea;
    private javax.swing.JTextArea popisKnihyTextArea;
    private javax.swing.JButton pridajAutoraButton;
    private javax.swing.JButton pridajKnihuButton;
    private javax.swing.JLabel priezviskoAutoraLabel;
    private javax.swing.JTextField priezviskoAutoraTextField;
    private javax.swing.JLabel stredneMenoAutoraLabel;
    private javax.swing.JTextField stredneMenoAutoraTextField;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JTextField urlTextField;
    private javax.swing.JButton vyhladajButton;
    private javax.swing.ButtonGroup vyhladajButtonGroup;
    private javax.swing.JComboBox<String> vyhladajComboBox;
    private javax.swing.JPanel vyhladavaciPanePanel;
    private javax.swing.ButtonGroup vyhladavajPodlaButtonGroup;
    private javax.swing.JLabel vyhladavajPodlaLabel;
    private javax.swing.JComboBox<String> zanerComboBox;
    private javax.swing.JLabel zanerLabel;
    private javax.swing.JRadioButton zanruRadioButton;
    private javax.swing.JButton zmenAutoraButton;
    private javax.swing.JButton zmenKnihuButton;
    // End of variables declaration//GEN-END:variables
}
