/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package sk.upjs.ics.paz1c.gui;

/**
 *
 * @author raven
 */
public class CitacOkno extends javax.swing.JFrame {

    
    /**
     * Creates new form CitacOkno
     */
    public CitacOkno() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zobrazovacScrollPane = new javax.swing.JScrollPane();
        naZaciatokButton = new javax.swing.JButton();
        predchadzajucaButton = new javax.swing.JButton();
        oddialButton = new javax.swing.JButton();
        ulozButton = new javax.swing.JButton();
        zavriButton = new javax.swing.JButton();
        priblizButton = new javax.swing.JButton();
        nachadzajucaButton = new javax.swing.JButton();
        naKoniecButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Virtuálna knižnica");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(950, 600));

        naZaciatokButton.setIcon(new javax.swing.ImageIcon("/home/raven/NetBeansProjects/VLib/arrowsL.png")); // NOI18N

        predchadzajucaButton.setIcon(new javax.swing.ImageIcon("/home/raven/NetBeansProjects/VLib/arrowL.png")); // NOI18N

        oddialButton.setIcon(new javax.swing.ImageIcon("/home/raven/NetBeansProjects/VLib/minus.png")); // NOI18N

        ulozButton.setText("Uložiť");

        zavriButton.setText("Zavrieť");

        priblizButton.setIcon(new javax.swing.ImageIcon("/home/raven/NetBeansProjects/VLib/plus.png")); // NOI18N
        priblizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priblizButtonActionPerformed(evt);
            }
        });

        nachadzajucaButton.setIcon(new javax.swing.ImageIcon("/home/raven/NetBeansProjects/VLib/arrowR.png")); // NOI18N

        naKoniecButton.setIcon(new javax.swing.ImageIcon("/home/raven/NetBeansProjects/VLib/arrowsR.png")); // NOI18N
        naKoniecButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                naKoniecButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zobrazovacScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(naZaciatokButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(predchadzajucaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(oddialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ulozButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(zavriButton)
                        .addGap(18, 18, 18)
                        .addComponent(priblizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nachadzajucaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(naKoniecButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(zobrazovacScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ulozButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priblizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nachadzajucaButton)
                            .addComponent(naKoniecButton)
                            .addComponent(naZaciatokButton)
                            .addComponent(predchadzajucaButton)
                            .addComponent(zavriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oddialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priblizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priblizButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priblizButtonActionPerformed

    private void naKoniecButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naKoniecButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_naKoniecButtonMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitacOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitacOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitacOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitacOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new CitacOkno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton naKoniecButton;
    private javax.swing.JButton naZaciatokButton;
    private javax.swing.JButton nachadzajucaButton;
    private javax.swing.JButton oddialButton;
    private javax.swing.JButton predchadzajucaButton;
    private javax.swing.JButton priblizButton;
    private javax.swing.JButton ulozButton;
    private javax.swing.JButton zavriButton;
    private javax.swing.JScrollPane zobrazovacScrollPane;
    // End of variables declaration//GEN-END:variables
}
