/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package sk.upjs.ics.paz1c.gui;

import java.util.List;
import sk.upjs.ics.paz1c.dao.AutorDao;
import sk.upjs.ics.paz1c.dao.KnihaDao;
import sk.upjs.ics.paz1c.dao.PouzivatelDao;
import sk.upjs.ics.paz1c.entity.Autor;
import sk.upjs.ics.paz1c.entity.Kniha;
import sk.upjs.ics.paz1c.entity.Pouzivatel;
import sk.upjs.ics.paz1c.pomocneTriedy.CitacVstupu;
import sk.upjs.ics.paz1c.pomocneTriedy.kombacik.KombacNasepkavac;
import sk.upjs.ics.paz1c.pomocneTriedy.kombacik.VyhladavatelnyRetazec;
import sk.upjs.ics.paz1c.tovaren.MagicFactory;

/**
 *
 * @author raven
 */
public class PridajKnihu extends javax.swing.JDialog {
    
    private AutorDao autorDao;
    
    private KnihaDao knihaDao;
    
    private PouzivatelDao pouzivatelDao;
    
    private List<String> nazvy;
    
    private List<String> autori;
    
    private List<String> zanre;
    
    private Long idPouzivatela;
    
    
    
    /**
     * Creates new form PK
     */
    public PridajKnihu(java.awt.Frame parent, boolean modal, Long id) {
        super(parent, modal);
        this.pouzivatelDao = MagicFactory.INSTANCE.pouzivatelDao();
        this.knihaDao = MagicFactory.INSTANCE.knihaDao();
        this.autorDao = MagicFactory.INSTANCE.autorDao();
        this.idPouzivatela = id;
        this.nazvy = knihaDao.nacitajKnihy();
        this.autori = autorDao.nacitajAutorov();
        this.zanre = knihaDao.nacitajZanre();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nazovLabel = new javax.swing.JLabel();
        urlLabel = new javax.swing.JLabel();
        zanerLabel = new javax.swing.JLabel();
        jazykLabel = new javax.swing.JLabel();
        foramtLabel = new javax.swing.JLabel();
        jazyk2Label = new javax.swing.JLabel();
        pocetStranLabel = new javax.swing.JLabel();
        popisKnihyLabel = new javax.swing.JLabel();
        menoAutorLabel = new javax.swing.JLabel();
        popisAutorLabel = new javax.swing.JLabel();
        nazovComboBox = new KombacNasepkavac(new VyhladavatelnyRetazec(nazvy));
        zanerComboBox = new KombacNasepkavac(new VyhladavatelnyRetazec(zanre));
        formatComboBox = new javax.swing.JComboBox<>();
        urlTextField = new javax.swing.JTextField();
        jazykTextField = new javax.swing.JTextField();
        jazyk2TextField = new javax.swing.JTextField();
        pocetStranTextField = new javax.swing.JTextField();
        popisKnihyTextField = new javax.swing.JTextField();
        popisAutoraTextField = new javax.swing.JTextField();
        pridajButton = new javax.swing.JButton();
        menoAutorTextField = new javax.swing.JTextField();
        priezviskoAutorTextField = new javax.swing.JTextField();
        stredneAutorTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pridaj knihu");
        setMaximumSize(new java.awt.Dimension(650, 550));
        setMinimumSize(new java.awt.Dimension(650, 550));
        setPreferredSize(new java.awt.Dimension(650, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 480));

        nazovLabel.setText("Názov:");

        urlLabel.setText("URL:");

        zanerLabel.setText("Žáner:");

        jazykLabel.setText("Jazyk:");

        foramtLabel.setText("Formát:");

        jazyk2Label.setText("Jazyk 2:");

        pocetStranLabel.setText("Počet strán:");

        popisKnihyLabel.setText("Popis knihy:");

        menoAutorLabel.setText("Meno:");

        popisAutorLabel.setText("Popis autora:");

        nazovComboBox.setEditable(true);

        formatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pdf", "epub", "mobi" }));

        popisAutoraTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popisAutoraTextFieldActionPerformed(evt);
            }
        });

        pridajButton.setText("Pridaj");
        pridajButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pridajButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("Priezvisko:");

        jLabel2.setText("Stredné:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(popisAutorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(popisAutoraTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(menoAutorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menoAutorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priezviskoAutorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stredneAutorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(popisKnihyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(popisKnihyTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pocetStranLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pocetStranTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jazyk2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jazyk2TextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jazykLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jazykTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nazovLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nazovComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(urlTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(zanerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zanerComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(foramtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formatComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(pridajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazovLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazovComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zanerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zanerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foramtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jazykLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jazykTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jazyk2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jazyk2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pocetStranLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pocetStranTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popisKnihyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(popisKnihyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menoAutorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menoAutorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priezviskoAutorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stredneAutorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(popisAutorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(popisAutoraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(pridajButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popisAutoraTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popisAutoraTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popisAutoraTextFieldActionPerformed

    private void pridajButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pridajButtonMouseClicked
        Autor autor;
        Long idZaner = 0L;
        try {
            autor = autorDao.najdiAutora(menoAutorTextField.getText(), priezviskoAutorTextField.getText(), stredneAutorTextField.getText());
        } catch (Exception e){
            autor = new Autor(menoAutorTextField.getText(), priezviskoAutorTextField.getText(), stredneAutorTextField.getText(), popisAutoraTextField.getText());
            autorDao.pridajAutora(autor);
            autor = autorDao.najdiAutora(menoAutorTextField.getText(), priezviskoAutorTextField.getText(), stredneAutorTextField.getText());
        }
        try {
            idZaner = nacitajIdZanru(zanerComboBox.getEditor().getItem().toString());
        } catch (Exception e) {
            knihaDao.pridajZaner(zanerComboBox.getEditor().getItem().toString());
            idZaner = nacitajIdZanru(zanerComboBox.getEditor().getItem().toString());
        }
        
        Kniha kniha = new Kniha(nazovComboBox.getEditor().getItem().toString(), autor.getIdAutor(),
                urlTextField.getText(), idPouzivatela, formatComboBox.getEditor().getItem().toString(), idZaner,
                jazykTextField.getText(), jazyk2TextField.getText(),  Long.parseLong(pocetStranTextField.getText()), popisKnihyTextField.getText());
        knihaDao.pridajKnihu(kniha);
        dispose();
    }//GEN-LAST:event_pridajButtonMouseClicked
    
    private Long nacitajIdZanru(String zaner) {
        return knihaDao.vratZaner(zaner);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PridajKnihu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PridajKnihu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PridajKnihu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PridajKnihu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PridajKnihu dialog = new PridajKnihu(new javax.swing.JFrame(), true, 4L);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel foramtLabel;
    private javax.swing.JComboBox<String> formatComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jazyk2Label;
    private javax.swing.JTextField jazyk2TextField;
    private javax.swing.JLabel jazykLabel;
    private javax.swing.JTextField jazykTextField;
    private javax.swing.JLabel menoAutorLabel;
    private javax.swing.JTextField menoAutorTextField;
    private javax.swing.JComboBox<String> nazovComboBox;
    private javax.swing.JLabel nazovLabel;
    private javax.swing.JLabel pocetStranLabel;
    private javax.swing.JTextField pocetStranTextField;
    private javax.swing.JLabel popisAutorLabel;
    private javax.swing.JTextField popisAutoraTextField;
    private javax.swing.JLabel popisKnihyLabel;
    private javax.swing.JTextField popisKnihyTextField;
    private javax.swing.JButton pridajButton;
    private javax.swing.JTextField priezviskoAutorTextField;
    private javax.swing.JTextField stredneAutorTextField;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JTextField urlTextField;
    private javax.swing.JComboBox<String> zanerComboBox;
    private javax.swing.JLabel zanerLabel;
    // End of variables declaration//GEN-END:variables
}
