/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.gui;

/**
 *
 * @author raven
 */
public class UvodneOkno extends javax.swing.JFrame {

    /**
     * Creates new form UvodneOkno
     */
    public UvodneOkno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        vyhladavajPodlaButtonGroup = new javax.swing.ButtonGroup();
        vyhladavaciPanePanel = new javax.swing.JPanel();
        vyhladavajPodlaLabel = new javax.swing.JLabel();
        nazvuRadioButton = new javax.swing.JRadioButton();
        zanruRadioButton = new javax.swing.JRadioButton();
        oblubenostiRadioButton = new javax.swing.JRadioButton();
        autoraRadioButton = new javax.swing.JRadioButton();
        jazykaRadioButton = new javax.swing.JRadioButton();
        formatuRadioButton = new javax.swing.JRadioButton();
        TabulkaScrollPane = new javax.swing.JScrollPane();
        tabulkaTable = new javax.swing.JTable();
        vyhladajComboBox = new javax.swing.JComboBox<>();
        vyhladajButton = new javax.swing.JButton();
        prihlasovaciPanel = new javax.swing.JPanel();
        prihlasovacieMenoTextField = new javax.swing.JTextField();
        hesloPasswordField = new javax.swing.JPasswordField();
        prihlasButton = new javax.swing.JButton();
        registrujButton = new javax.swing.JButton();
        oKnihePanel = new javax.swing.JPanel();
        oKniheScrollPane = new javax.swing.JScrollPane();
        popisKnihyTextArea = new javax.swing.JTextArea();
        fotkaAutoraLabel = new javax.swing.JLabel();
        menoAutoraLabel = new javax.swing.JLabel();
        oAutoroviScrollPane = new javax.swing.JScrollPane();
        popisAutoraTextArea = new javax.swing.JTextArea();
        pocetStranLabel = new javax.swing.JLabel();
        formatKnihyLabel = new javax.swing.JLabel();
        citajButton = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Virtuálna knižnica");
        setMinimumSize(new java.awt.Dimension(900, 710));

        vyhladavajPodlaLabel.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        vyhladavajPodlaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vyhladavajPodlaLabel.setText("Vyhľadávať podľa:");

        vyhladavajPodlaButtonGroup.add(nazvuRadioButton);
        nazvuRadioButton.setSelected(true);
        nazvuRadioButton.setText("Názvu");
        nazvuRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazvuRadioButtonActionPerformed(evt);
            }
        });

        vyhladavajPodlaButtonGroup.add(zanruRadioButton);
        zanruRadioButton.setText("Žánru");

        vyhladavajPodlaButtonGroup.add(oblubenostiRadioButton);
        oblubenostiRadioButton.setText("Obľúbenosti");

        vyhladavajPodlaButtonGroup.add(autoraRadioButton);
        autoraRadioButton.setText("Autora");
        autoraRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoraRadioButtonActionPerformed(evt);
            }
        });

        vyhladavajPodlaButtonGroup.add(jazykaRadioButton);
        jazykaRadioButton.setText("Jazyka");

        vyhladavajPodlaButtonGroup.add(formatuRadioButton);
        formatuRadioButton.setText("Formátu");

        javax.swing.GroupLayout vyhladavaciPanePanelLayout = new javax.swing.GroupLayout(vyhladavaciPanePanel);
        vyhladavaciPanePanel.setLayout(vyhladavaciPanePanelLayout);
        vyhladavaciPanePanelLayout.setHorizontalGroup(
            vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vyhladavaciPanePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vyhladavajPodlaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addGroup(vyhladavaciPanePanelLayout.createSequentialGroup()
                        .addGroup(vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nazvuRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zanruRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oblubenostiRadioButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vyhladavaciPanePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formatuRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autoraRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jazykaRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        vyhladavaciPanePanelLayout.setVerticalGroup(
            vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vyhladavaciPanePanelLayout.createSequentialGroup()
                .addComponent(vyhladavajPodlaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazvuRadioButton)
                    .addComponent(autoraRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zanruRadioButton)
                    .addComponent(jazykaRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vyhladavaciPanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oblubenostiRadioButton)
                    .addComponent(formatuRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabulkaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabulkaScrollPane.setViewportView(tabulkaTable);

        vyhladajComboBox.setEditable(true);
        vyhladajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        vyhladajButton.setText("Hľadaj");
        vyhladajButton.setMaximumSize(new java.awt.Dimension(90, 35));
        vyhladajButton.setMinimumSize(new java.awt.Dimension(90, 35));

        prihlasovacieMenoTextField.setText("Meno");
        prihlasovacieMenoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prihlasovacieMenoTextFieldActionPerformed(evt);
            }
        });

        hesloPasswordField.setText("jPasswordField1");

        prihlasButton.setText("Prihlás sa");

        registrujButton.setText("Registruj sa");
        registrujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrujButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout prihlasovaciPanelLayout = new javax.swing.GroupLayout(prihlasovaciPanel);
        prihlasovaciPanel.setLayout(prihlasovaciPanelLayout);
        prihlasovaciPanelLayout.setHorizontalGroup(
            prihlasovaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prihlasovaciPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prihlasovaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hesloPasswordField)
                    .addComponent(prihlasovacieMenoTextField)
                    .addGroup(prihlasovaciPanelLayout.createSequentialGroup()
                        .addComponent(prihlasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrujButton, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                .addContainerGap())
        );
        prihlasovaciPanelLayout.setVerticalGroup(
            prihlasovaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prihlasovaciPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prihlasovacieMenoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hesloPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(prihlasovaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prihlasButton)
                    .addComponent(registrujButton)))
        );

        popisKnihyTextArea.setEditable(false);
        popisKnihyTextArea.setColumns(20);
        popisKnihyTextArea.setRows(5);
        popisKnihyTextArea.setText("Popis knihy");
        oKniheScrollPane.setViewportView(popisKnihyTextArea);

        fotkaAutoraLabel.setText("Fotka autora");

        menoAutoraLabel.setText("Meno autora");

        oAutoroviScrollPane.setMaximumSize(new java.awt.Dimension(130, 130));

        popisAutoraTextArea.setEditable(false);
        popisAutoraTextArea.setColumns(20);
        popisAutoraTextArea.setRows(5);
        popisAutoraTextArea.setText("O autorovi");
        popisAutoraTextArea.setToolTipText("");
        popisAutoraTextArea.setMaximumSize(new java.awt.Dimension(130, 75));
        popisAutoraTextArea.setPreferredSize(new java.awt.Dimension(150, 75));
        oAutoroviScrollPane.setViewportView(popisAutoraTextArea);

        pocetStranLabel.setText("Počet strán");

        formatKnihyLabel.setText("Formát knihy");

        javax.swing.GroupLayout oKnihePanelLayout = new javax.swing.GroupLayout(oKnihePanel);
        oKnihePanel.setLayout(oKnihePanelLayout);
        oKnihePanelLayout.setHorizontalGroup(
            oKnihePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oKnihePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oKnihePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oKniheScrollPane)
                    .addGroup(oKnihePanelLayout.createSequentialGroup()
                        .addGroup(oKnihePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(oAutoroviScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(oKnihePanelLayout.createSequentialGroup()
                                .addGroup(oKnihePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(menoAutoraLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(pocetStranLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(formatKnihyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fotkaAutoraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );
        oKnihePanelLayout.setVerticalGroup(
            oKnihePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oKnihePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oKnihePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oKnihePanelLayout.createSequentialGroup()
                        .addComponent(menoAutoraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pocetStranLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formatKnihyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fotkaAutoraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oAutoroviScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oKniheScrollPane))
        );

        citajButton.setText("Čítaj knihu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vyhladajComboBox, 0, 495, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(vyhladajButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TabulkaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(prihlasovaciPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(oKnihePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(vyhladavaciPanePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(citajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vyhladajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vyhladajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(TabulkaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vyhladavaciPanePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prihlasovaciPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(citajButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oKnihePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void autoraRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoraRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoraRadioButtonActionPerformed

    private void registrujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrujButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrujButtonActionPerformed

    private void nazvuRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazvuRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nazvuRadioButtonActionPerformed

    private void prihlasovacieMenoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prihlasovacieMenoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prihlasovacieMenoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UvodneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UvodneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UvodneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UvodneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UvodneOkno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TabulkaScrollPane;
    private javax.swing.JRadioButton autoraRadioButton;
    private javax.swing.JButton citajButton;
    private javax.swing.JLabel formatKnihyLabel;
    private javax.swing.JRadioButton formatuRadioButton;
    private javax.swing.JLabel fotkaAutoraLabel;
    private javax.swing.JPasswordField hesloPasswordField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JRadioButton jazykaRadioButton;
    private javax.swing.JLabel menoAutoraLabel;
    private javax.swing.JRadioButton nazvuRadioButton;
    private javax.swing.JScrollPane oAutoroviScrollPane;
    private javax.swing.JPanel oKnihePanel;
    private javax.swing.JScrollPane oKniheScrollPane;
    private javax.swing.JRadioButton oblubenostiRadioButton;
    private javax.swing.JLabel pocetStranLabel;
    private javax.swing.JTextArea popisAutoraTextArea;
    private javax.swing.JTextArea popisKnihyTextArea;
    private javax.swing.JButton prihlasButton;
    private javax.swing.JPanel prihlasovaciPanel;
    private javax.swing.JTextField prihlasovacieMenoTextField;
    private javax.swing.JButton registrujButton;
    private javax.swing.JTable tabulkaTable;
    private javax.swing.JButton vyhladajButton;
    private javax.swing.JComboBox<String> vyhladajComboBox;
    private javax.swing.JPanel vyhladavaciPanePanel;
    private javax.swing.ButtonGroup vyhladavajPodlaButtonGroup;
    private javax.swing.JLabel vyhladavajPodlaLabel;
    private javax.swing.JRadioButton zanruRadioButton;
    // End of variables declaration//GEN-END:variables
}
